Repository TeamHARA/KAERA_iOS, pull requests merged in 2023-11, with the labels that each got.

#80 [Feat] 고민수정 API 연결
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Network/APIs/WriteAPI.swift
  KAERA/KAERA/Network/Services/HomeService.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
  KAERA/KAERA/Scenes/Home/Model/WorryDetailModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/KaeraTabbarController.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentHeaderView.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTVC.swift
  KAERA/KAERA/Scenes/Writing/View/WorryPatchManager.swift
  KAERA/KAERA/Scenes/Writing/View/WorryPostManager.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 💎 Chore, ✈️ Network, 💼 Logic

#84 [Feat] 고민 완료 API 연결
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Network/Services/HomeService.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Home/Model/CompleteWorryModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDecisionVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryQuoteView.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
Labels: ✈️ Network

#81 [Feat] 카카오 로그아웃 API 연결 + 보관함 NaviBar 변경
  KAERA/KAERA/Global/Base/BaseVC.swift
  KAERA/KAERA/Network/APIs/AuthAPI.swift
  KAERA/KAERA/Network/Base/APIConstant.swift
  KAERA/KAERA/Network/Services/AuthService.swift
  KAERA/KAERA/Resources/Assets.xcassets/Icons/icn_template_info.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/Icons/icn_template_info.imageset/icn_template_info.pdf
  KAERA/KAERA/Resources/Assets.xcassets/Icons/icn_template_info.imageset/icon design.pdf
  KAERA/KAERA/Scenes/Archive/View/ArchiveHeaderView.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Auth/Model/MyPageDataType.swift
  KAERA/KAERA/Scenes/Auth/View/MyPageTVC.swift
  KAERA/KAERA/Scenes/Auth/View/MyPageTVFooterView.swift
  KAERA/KAERA/Scenes/Auth/View/MyPageVC.swift
  KAERA/KAERA/Scenes/Auth/ViewModel/MyPaggeViewModel.swift
  KAERA/KAERA/Scenes/Components/CustomNavigationBarView.swift
Labels: ✈️ Network, 🖼️ UI

#85 [Feat] 애플 로그인 API 연결
  KAERA/KAERA/Application/KeyChainManager.swift
  KAERA/KAERA/Network/APIs/AuthAPI.swift
  KAERA/KAERA/Network/Base/APIConstant.swift
  KAERA/KAERA/Network/Services/AuthService.swift
  KAERA/KAERA/Scenes/Auth/Model/SignInModel.swift
  KAERA/KAERA/Scenes/Auth/ViewModel/SignInViewModel.swift
  KAERA/KAERA/Scenes/Splash/View/SplashVC.swift
Labels: ✈️ Network

#91 [Feat] 고민개수 12개일때 고민작성 제한
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Scenes/Components/KaeraAlertVC.swift
  KAERA/KAERA/Scenes/Home/Model/HomeGemStoneCount.swift
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/HomeGemStoneVC.swift
  KAERA/KAERA/Scenes/KaeraTabbarController.swift
Labels: 🖼️ UI

#92 [Chore] 고민보관함 초기화, 상세보기 더보기 창 case 나누기, 데드라인 설정하지 않기 버튼 활성화
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
Labels: 💎 Chore, 💼 Logic

#94 [Chore] 1차 QA 반영(UI)
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDecisionVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryQuoteView.swift
  KAERA/KAERA/Scenes/KaeraTabbarController.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
Labels: 💎 Chore, 🖼️ UI, ✏️ QA

#96 [Chore] 1차 QA 반영(Logic)
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoHeaderView.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
  KAERA/KAERA/Scenes/Components/CustomNavigationBarView.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 💼 Logic, ✏️ QA

#99 [Chore] 홈 고민 목록 조회 URI 수정사항 적용
  KAERA/KAERA/Network/Base/APIConstant.swift
  KAERA/KAERA/Network/Services/HomeService.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 🐞 Bug & Fix, 💎 Chore

#101 [Chore] 로그인 요청시 request에 deviceToken 추가
  KAERA/KAERA/Application/AppDelegate.swift
  KAERA/KAERA/Network/Services/AuthService.swift
  KAERA/KAERA/Scenes/Auth/Model/SignInModel.swift
  KAERA/KAERA/Scenes/Auth/View/SignInVC.swift
  KAERA/KAERA/Scenes/Auth/ViewModel/SignInViewModel.swift
Labels: 💎 Chore

#104 [Feat] Interceptor를 이용한 토큰 갱신 로직 추가
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Network/APIs/ArchiveAPI.swift
  KAERA/KAERA/Network/APIs/AuthAPI.swift
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Network/APIs/WriteAPI.swift
  KAERA/KAERA/Network/Base/AuthInterceptor.swift
  KAERA/KAERA/Network/Services/ArchiveService.swift
  KAERA/KAERA/Network/Services/AuthService.swift
  KAERA/KAERA/Network/Services/HomeService.swift
  KAERA/KAERA/Network/Services/WriteService.swift
Labels: ✈️ Network, 💼 Logic

#106 [Refactor] 고민 수정 관련 버그 및 QA 수정
  KAERA/KAERA.xcodeproj/xcshareddata/xcschemes/KAERA.xcscheme
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
  KAERA/KAERA/Scenes/Components/CustomNavigationBarView.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTVC.swift
  KAERA/KAERA/Scenes/Writing/View/WorryPatchManager.swift
  KAERA/KAERA/Scenes/Writing/View/WorryPostManager.swift
  KAERA/KAERA/Scenes/Writing/View/WriteModal/WriteModalVC.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 🐞 Bug & Fix, 💎 Chore, 💼 Logic, ✏️ QA

#108 [Chore] 온보딩 연결 및 로그아웃 임시 처리
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Application/SceneDelegate.swift
  KAERA/KAERA/Scenes/Auth/View/MyPageVC.swift
  KAERA/KAERA/Scenes/Auth/ViewModel/MyPaggeViewModel.swift
  KAERA/KAERA/Scenes/Onboarding/View/OnboardingVC.swift
  KAERA/KAERA/Scenes/Splash/View/SplashVC.swift
Labels: 💎 Chore, ✏️ QA

#110 [Feat] 앱 처음 실행시 키체인 데이터 초기화 로직 추가
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Application/AppDelegate.swift
  KAERA/KAERA/Global/Extensions/UserDefaults+.swift
Labels: 💼 Logic
