Repository TeamHARA/KAERA_iOS, pull requests merged in 2023-12, with the labels that each got.

#116 [Feat] 캐라 서버 요청 로딩 뷰 추가
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAERA/KAERA/Global/Base/BaseVC.swift
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Resources/Animations/kaera_loading.json
  KAERA/KAERA/Scenes/Archive/View/ArchiveModal/ArchiveModalVC.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Archive/ViewModel/WorryListViewModel.swift
  KAERA/KAERA/Scenes/Auth/View/MyPageVC.swift
  KAERA/KAERA/Scenes/Auth/View/SignInVC.swift
  KAERA/KAERA/Scenes/Home/Model/EditWorryResponseModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/HomeGemStoneVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDecisionVC.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeGemListViewModel.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateContentViewModel.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateViewModel.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
  KAERA/KAERA/Scenes/Writing/View/WriteModal/WriteModalVC.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 💎 Chore, 🖼️ UI, 💼 Logic

#117 [Fix] 고민 작성 제한 조건 수정
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/HomeGemStoneVC.swift
Labels: 🐞 Bug & Fix

#124 [Fix] 템플릿 정보 작성하러가기 시 template 조회 아이디 수정
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoTVC.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
Labels: 🐞 Bug & Fix

#129 [Fix] 데드라인 관련 로직 수정
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTVC.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
Labels: 🐞 Bug & Fix, 💼 Logic

#132 [Fix] 데드라인 설정하지 않기 데이터 전달 버그 수정
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailFooterView.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
Labels: 🐞 Bug & Fix

#133 [Fix] 나의 기록 수정 날짜 표시 로직수정
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDetailReviewView.swift
Labels: 🐞 Bug & Fix

#135 [Fix] 고민 캐기 최종답변 관련 버그 수정
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDecisionVC.swift
Labels: 🐞 Bug & Fix

#137 [Fix] 고민작성 제목, 답변 델리게이트 로직 수정
  KAERA/KAERA/Scenes/Writing/View/TemplateContentHeaderView.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTVC.swift
Labels: 🐞 Bug & Fix

#138 [Feat] 캐라 인스타그램 계정 연결
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoHeaderView.swift
Labels: 💎 Chore, 💼 Logic

#140 [Feat] 오픈소스 라이센스 명시
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/Settings.bundle/LicenseProject.latest_result.txt
  KAERA/Settings.bundle/LicenseProject.plist
  KAERA/Settings.bundle/LicenseProject/Alamofire.plist
  KAERA/Settings.bundle/LicenseProject/GoogleAppMeasurement.plist
  KAERA/Settings.bundle/LicenseProject/GoogleDataTransport.plist
  KAERA/Settings.bundle/LicenseProject/GoogleUtilities.plist
  KAERA/Settings.bundle/LicenseProject/Moya.plist
  KAERA/Settings.bundle/LicenseProject/ReactiveSwift.plist
  KAERA/Settings.bundle/LicenseProject/RxSwift.plist
  KAERA/Settings.bundle/LicenseProject/SnapKit.plist
  KAERA/Settings.bundle/LicenseProject/Then.plist
  KAERA/Settings.bundle/LicenseProject/abseil-cpp-binary.plist
  KAERA/Settings.bundle/LicenseProject/firebase-ios-sdk.plist
  KAERA/Settings.bundle/LicenseProject/grpc-binary.plist
  KAERA/Settings.bundle/LicenseProject/gtm-session-fetcher.plist
  KAERA/Settings.bundle/LicenseProject/interop-ios-for-google-sdks.plist
  KAERA/Settings.bundle/LicenseProject/kakao-ios-sdk.plist
  KAERA/Settings.bundle/LicenseProject/leveldb.plist
  KAERA/Settings.bundle/LicenseProject/lottie-ios.plist
  KAERA/Settings.bundle/LicenseProject/nanopb.plist
  KAERA/Settings.bundle/LicenseProject/promises.plist
  KAERA/Settings.bundle/LicenseProject/swift-protobuf.plist
  KAERA/Settings.bundle/Root.plist
  KAERA/Settings.bundle/en.lproj/Root.strings
Labels: 💎 Chore, 📜 Docs

#143 [Fix] 고민수정 시 기존 답변 내용 적용 안됨 버그 수정
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTVC.swift
Labels: 🐞 Bug & Fix

#150 [Fix] 고민작성API 리스폰스 수정
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Network/APIs/WriteAPI.swift
  KAERA/KAERA/Scenes/Archive/Model/TemplateContentModel.swift
  KAERA/KAERA/Scenes/Archive/Model/WorryContentResponseModel.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
Labels: 🐞 Bug & Fix, ✈️ Network

#153 [Fix] 고민 상세 API 리스폰스 변경 사항 반영
  KAERA/KAERA/Scenes/Home/Model/WorryDetailModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
Labels: 💎 Chore

#155 [Chore] 마이페이지 연결 링크 적용
  KAERA/KAERA/Scenes/Auth/ViewModel/MyPaggeViewModel.swift
Labels: 💎 Chore

#152 [Fix] 고민작성 시 제목 마지막 글자 자/모 분리 문제 해결
  KAERA/KAERA/Scenes/Writing/View/TemplateContentHeaderView.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
Labels: 🐞 Bug & Fix

#154 [Fix] 고민 상세보기 배경화면 수정
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/RadialGradientView.swift
Labels: 🐞 Bug & Fix

#158 [Fix] 고민작성 내 템플릿 변경시 templateId 반영 안되는 이슈
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 🐞 Bug & Fix

#160 [Fix] 고민수정 시 완료 버튼 활성화되게끔 변경
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 🐞 Bug & Fix

#161 [Fix] 글 삭제 시 고민보관함 reload 안되는 이슈 해결
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
Labels: 🐞 Bug & Fix

#163 [Feat] 고민 작성시 고민 상세 이동 로직 구현
  KAERA/KAERA/Scenes/Auth/Model/MyPageDataType.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDecisionVC.swift
  KAERA/KAERA/Scenes/KaeraTabbarController.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
Labels: 🖼️ UI, 💼 Logic

#165 [ Fix] 고민 상세 리스폰스 수정 및 리뷰 텍스트 버그 수정
  KAERA/KAERA/Scenes/Home/Model/WorryDetailModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDetailReviewView.swift
Labels: 🐞 Bug & Fix, 💎 Chore

#167 [Feat] 빌드별 스키마 설정
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA.xcodeproj/xcshareddata/xcschemes/KAERA-Debug.xcscheme
  KAERA/KAERA.xcodeproj/xcshareddata/xcschemes/KAERA-QA.xcscheme
  KAERA/KAERA.xcodeproj/xcshareddata/xcschemes/KAERA-Release.xcscheme
Labels: 💎 Chore

#168 [Fix] 토큰 갱신 interceptor retry 버그 수정
  KAERA/KAERA/Network/Base/AuthInterceptor.swift
  KAERA/KAERA/Network/Base/BaseTargetType.swift
Labels: 🐞 Bug & Fix
