Repository TeamHARA/KAERA_iOS, pull requests merged in 2023-09, with the labels that each got.

#37 [Feat] 고민보관함뷰 고민리스트 조회 API 연결
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Network/APIs/ArchiveAPI.swift
  KAERA/KAERA/Network/Base/APIConstant.swift
  KAERA/KAERA/Network/Services/ArchiveService.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveModal/ArchiveModalCVC.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveModal/ArchiveModalVC.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Archive/ViewModel/WorryListViewModel.swift
  KAERA/KAERA/Scenes/Writing/Model/WorryListModel.swift
Labels: ✈️ Network, 💼 Logic

#39 [Feat] 템플릿 종류 조회하기 API 연결
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Network/APIs/WriteAPI.swift
  KAERA/KAERA/Network/Base/APIConstant.swift
  KAERA/KAERA/Network/Services/WriteService.swift
  KAERA/KAERA/Scenes/Archive/Model/TemplateListModel.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveModal/ArchiveModalVC.swift
  KAERA/KAERA/Scenes/Archive/ViewModel/WorryListViewModel.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateViewModel.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteModal/WriteModalVC.swift
Labels: ✈️ Network, 💼 Logic

#41 [Feat] 고민보관함탭 고민작성지뷰 템플릿 종류 조회하기 API 연결
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateViewModel.swift
Labels: ✈️ Network

#43 [Feat] 고민작성뷰 템플릿별 질문 조회하기 API 연결
  KAERA/KAERA/Network/APIs/ArchiveAPI.swift
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Network/APIs/WriteAPI.swift
  KAERA/KAERA/Network/Services/WriteService.swift
  KAERA/KAERA/Scenes/Archive/Model/TemplateContentModel.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateContentViewModel.swift
Labels: ✈️ Network

#48 [Hot Fix] 브랜치 re-merge
  KAERA/KAERA/Network/APIs/ArchiveAPI.swift
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Network/APIs/WriteAPI.swift
  KAERA/KAERA/Network/Services/WriteService.swift
  KAERA/KAERA/Scenes/Archive/Model/TemplateContentModel.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateContentViewModel.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateViewModel.swift
Labels: 🐞 Bug & Fix

#50 [Chore] templateInfoModel과 templateListModel 병합 및 templateVM 수정
  KAERA/KAERA/Network/Base/APIConstant.swift
  KAERA/KAERA/Network/Services/ArchiveService.swift
  KAERA/KAERA/Network/Services/HomeService.swift
  KAERA/KAERA/Network/Services/WriteService.swift
  KAERA/KAERA/Scenes/Archive/Model/TemplateListModel.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveModal/ArchiveModalCVC.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveModal/ArchiveModalVC.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateViewModel.swift
  KAERA/KAERA/Scenes/Writing/View/WriteModal/WriteModalCVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteModal/WriteModalVC.swift
Labels: 💎 Chore, 💼 Logic

#52 [Fix] templateInfoVC와 templateVM 연결부분 수정
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
Labels: 🐞 Bug & Fix, 💼 Logic

#46 [Feat] 고민 상세뷰 API 연결 및 기타 홈, 상세 코드 수정
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Network/Services/HomeService.swift
  KAERA/KAERA/Scenes/Home/Model/WorryDetailModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/HomeGemStoneVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailFooterView.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailTVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDetailReviewView.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
Labels: 🐞 Bug & Fix, 💎 Chore, ✈️ Network, 🖼️ UI

#53 [Feat] 소셜 로그인(카카오, 애플) 구현 (토큰 전달 전까지)
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KAERA/KAERA/Application/AppDelegate.swift
  KAERA/KAERA/Application/Environment.swift
  KAERA/KAERA/Application/Info.plist
  KAERA/KAERA/Application/SceneDelegate.swift
  KAERA/KAERA/KAERA.entitlements
  KAERA/KAERA/Resources/Assets.xcassets/GemsAndStones/signInGems.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/GemsAndStones/signInGems.imageset/signInGems.pdf
  KAERA/KAERA/Resources/Assets.xcassets/SingIn/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/SingIn/appleLoginButton.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/SingIn/appleLoginButton.imageset/appleLoginButton.pdf
  KAERA/KAERA/Resources/Assets.xcassets/SingIn/kakaoLoginButton.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/SingIn/kakaoLoginButton.imageset/kakaoLoginButton.pdf
  KAERA/KAERA/Scenes/Auth/SignInVC.swift
Labels: 💎 Chore, 🖼️ UI

#55 [Feat] 고민 편집 창 구현
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
Labels: 🖼️ UI

#57 [Feat] 캐라 알림창 구현
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Resources/Assets.xcassets/Icons/icn_alert.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/Icons/icn_alert.imageset/alert_icn.pdf
  KAERA/KAERA/Scenes/Components/KaeraAlertVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryEditVC.swift
Labels: 🖼️ UI

#60 [Feat] 고민보관함 뷰에서 고민 클릭시 상세보기 뷰로 가는 로직 구현
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Archive/View/WorryListCVC.swift
  KAERA/KAERA/Scenes/Archive/ViewModel/WorryListViewModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailHeaderView.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeGemListViewModel.swift
  KAERA/KAERA/Scenes/Writing/Model/WorryListModel.swift
Labels: 💼 Logic
