Repository TeamHARA/KAERA_iOS, pull requests merged in 2023-08, with the labels that each got.

#25 [Feat] 고민작성지 뷰(템플릿 상세보기뷰) ViewModel 구현
  KAERA/KAERA/Scenes/Archive/Model/TemplateListModel.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoTVC.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateViewModel.swift
Labels: 🖼️ UI, 💼 Logic

#26 [Feat] 고민완료 상세 뷰 구현
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Resources/Assets.xcassets/seperate_left.imageset/seperate_left.pdf
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/GemStoneCVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/HomeGemStoneVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailFooterView.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailHeaderView.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailTVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDetailReviewView.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
Labels: 🖼️ UI

#29 [Feat] 고민작성뷰 템플릿에 맞는 질문지 리스트 불러오기 뷰 구현
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Scenes/Archive/Model/TemplateContentModel.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoTVC.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Components/CustomNavigationBarView.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateContentViewModel.swift
  KAERA/KAERA/Scenes/ViewModel/TemplateViewModel.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentHeaderView.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteModal/WriteModalVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 🖼️ UI, 💼 Logic

#30 [Feat] 고민 캐기 창 및 캐기완료 메시지 창 구현
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDecisionVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryQuoteView.swift
Labels: 🖼️ UI

#33 [Feat] 네트워크 기본 세팅 & 홈 고민목록 조회 API 서버연결
  .gitignore
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Application/Info.plist
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Network/APIs/Temp_API.swift
  KAERA/KAERA/Network/Base/APIConstant.swift
  KAERA/KAERA/Network/Base/NetworkConstant.swift
  KAERA/KAERA/Network/Services/HomeService.swift
  KAERA/KAERA/Network/Services/Temp_Service.swift
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/HomeGemStoneVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDecisionVC.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeGemListViewModel.swift
Labels: 💎 Chore, ✈️ Network

#34 [Feat] 고민작성뷰 키보드 동작 구현
  KAERA/KAERA/Scenes/Archive/Model/TemplateContentModel.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveModal/ArchiveModalVC.swift
  KAERA/KAERA/Scenes/Archive/ViewModel/WorryListViewModel.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentHeaderView.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTV.swift
  KAERA/KAERA/Scenes/Writing/View/TemplateContentTVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteModal/WriteModalVC.swift
  KAERA/KAERA/Scenes/Writing/View/WriteVC.swift
Labels: 🖼️ UI, 💼 Logic
