Repository TeamHARA/KAERA_iOS, pull requests merged in 2024-01, with the labels that each got.

#171 [Fix] 카카오톡 미설치 된 기기 로그인 시 웹 로그인 실행
  KAERA/KAERA/Scenes/Auth/ViewModel/SignInViewModel.swift
Labels: 🐞 Bug & Fix

#177 [Fix] 고민 길이 길때 답변 색상 달라지는 오류 수정
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
Labels: 🐞 Bug & Fix

#181 [Chore] 고민 상세 뷰 데이터 전달 수정
  KAERA/KAERA/Scenes/Archive/Model/WorryContentResponseModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Writing/View/WritePickerVC.swift
Labels: 💎 Chore

#185 [Feat] 고민 캐기 후 완료된 고민 상세로 이동 구현
  KAERA/KAERA/Scenes/Home/View/HomeVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/WorryDecisionVC.swift
Labels: 💼 Logic

#186 [Fix] retry로 토큰 갱신시 요청 헤더 미 갱신 이슈 수정
  KAERA/KAERA/Application/AppDelegate.swift
  KAERA/KAERA/Network/Base/AuthInterceptor.swift
  KAERA/KAERA/Network/Base/NetworkConstant.swift
Labels: 🐞 Bug & Fix, ✈️ Network, 💼 Logic

#188 [Feat] 푸시 메시지를 통한 고민상세로 화면전환
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Application/AppDelegate.swift
  KAERA/KAERA/Application/Info.plist
  KAERA/KAERA/Application/SceneDelegate.swift
  KAERA/KAERA/Global/Extensions/UIViewController+.swift
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/HomeGemStoneVC.swift
  KAERA/KAERA/Scenes/Splash/Model/LaunchingWithPushMessage.swift
Labels: 💼 Logic

#189 [Chore] 인스타그램 배너 이미지 변경
  KAERA/KAERA/Resources/Assets.xcassets/GemsAndStones/Gems/gems.imageset/gems.pdf
  KAERA/KAERA/Resources/Assets.xcassets/Icons/insta_back.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/Icons/insta_back.imageset/insta_back.pdf
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoHeaderView.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveTemplateInfo/TemplateInfoVC.swift
Labels: 💎 Chore, 🖼️ UI

#190 [Feat] 네트워크/인앱 에러시 새로고침 화면 구현
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Resources/Assets.xcassets/Icons/app_error.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/Icons/app_error.imageset/Group 986645.pdf
  KAERA/KAERA/Resources/Assets.xcassets/Icons/app_error_btn.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/Icons/app_error_btn.imageset/Group 986635.pdf
  KAERA/KAERA/Resources/Assets.xcassets/Icons/internet_error.imageset/Contents.json
  KAERA/KAERA/Resources/Assets.xcassets/Icons/internet_error.imageset/internetError.pdf
  KAERA/KAERA/Scenes/Components/ErrorCase.swift
  KAERA/KAERA/Scenes/Components/ErrorView.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
Labels: 🖼️ UI, 💼 Logic

#194 [Chore] 애플 로그인 요청 정보 이메일 제외
  KAERA/KAERA/Scenes/Auth/ViewModel/SignInViewModel.swift
Labels: 💎 Chore

#196 [Chore] MoyaProvider의 세션의 configuration 설정
  KAERA/KAERA.xcodeproj/project.pbxproj
  KAERA/KAERA/Network/APIs/ArchiveAPI.swift
  KAERA/KAERA/Network/APIs/AuthAPI.swift
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Network/APIs/WriteAPI.swift
  KAERA/KAERA/Network/Base/MoyaSession.swift
Labels: 💎 Chore

#199 [Feat] 고민보관함 네트워크/인앱 에러뷰 적용
  KAERA/KAERA/Network/APIs/ArchiveAPI.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Archive/ViewModel/WorryListViewModel.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
Labels: 💼 Logic

#200 [Feat] 홈 에러뷰 추가 및 combine 구독 이슈 수정
  KAERA/KAERA/Network/APIs/HomeAPI.swift
  KAERA/KAERA/Scenes/Archive/View/ArchiveVC.swift
  KAERA/KAERA/Scenes/Archive/ViewModel/WorryListViewModel.swift
  KAERA/KAERA/Scenes/Components/ErrorView.swift
  KAERA/KAERA/Scenes/Home/View/HomeGemStone/HomeGemStoneVC.swift
  KAERA/KAERA/Scenes/Home/View/HomeWorryDetail/HomeWorryDetailVC.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeGemListViewModel.swift
  KAERA/KAERA/Scenes/Home/ViewModel/HomeWorryDetailViewModel.swift
Labels: 🐞 Bug & Fix, 💼 Logic
